<a href="https://colab.research.google.com/github/Sunkara-saivardhan/ANN-Airline-Passenger-Satisfaction-Prediction/blob/main/ANN_with_classfication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import keras
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize, LabelEncoder, StandardScaler, OneHotEncoder

In [6]:
data=pd.read_csv("/content/airline_passenger_satisfaction.csv")
data.shape

(129880, 24)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ID                                      129880 non-null  int64
 1   Gender                                  129880 non-null  object
 2   Age                                     129880 non-null  int64
 3   Customer Type                           129880 non-null  object
 4   Type of Travel                          129880 non-null  object
 5   Class                                   129880 non-null  object
 6   Flight Distance                         129880 non-null  int64
 7   Departure Delay                         129880 non-null  int64
 8   Arrival Delay                           129487 non-null  float64
 9   Departure and Arrival Time Convenience  129880 non-null  int64
 10  Ease of Online Booking                  129880 non-null  int64
 11  Check-in Service                        129880 non-null  int64
 12  Online Boarding                         129880 non-null  int64
 13  Gate Location                           129880 non-null  int64
 14  On-board Service                        129880 non-null  int64
 15  Seat Comfort                            129880 non-null  int64
 16  Leg Room Service                        129880 non-null  int64
 17  Cleanliness                             129880 non-null  int64
 18  Food and Drink                          129880 non-null  int64
 19  In-flight Service                       129880 non-null  int64
 20  In-flight Wifi Service                  129880 non-null  int64
 21  In-flight Entertainment                 129880 non-null  int64
 22  Baggage Handling                        129880 non-null  int64
 23  Satisfaction                            129880 non-null  object
dtypes: float64(1), int64(18), object(5)
memory usage: 23.8+ MB

In [8]:
data.describe()

,ID,Age,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling
count,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000
mean,64940.500000,39.427957,1190.316392,14.713713,15.091129,3.057599,2.756876,3.306267,3.252633,2.976925,3.383023,3.441361,3.350878,3.286326,3.204774,3.642193,2.728696,3.358077,3.632114
std,37493.270818,15.119360,997.452477,38.071126,38.465650,1.526741,1.401740,1.266185,1.350719,1.278520,1.287099,1.319289,1.316252,1.313682,1.329933,1.176669,1.329340,1.334049,1.180025
min,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,32470.750000,27.000000,414.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,3.000000
50%,64940.500000,40.000000,844.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
75%,97410.250000,51.000000,1744.000000,12.000000,13.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,5.000000
max,129880.000000,85.000000,4983.000000,1592.000000,1584.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [9]:
print(data.head(10))
print(data.tail(10))

   ID  Gender  Age Customer Type Type of Travel     Class  Flight Distance  \
0   1    Male   48    First-time       Business  Business              821
1   2  Female   35     Returning       Business  Business              821
2   3    Male   41     Returning       Business  Business              853
3   4    Male   50     Returning       Business  Business             1905
4   5  Female   49     Returning       Business  Business             3470
5   6    Male   43     Returning       Business  Business             3788
6   7    Male   43     Returning       Business  Business             1963
7   8  Female   60     Returning       Business  Business              853
8   9    Male   50     Returning       Business  Business             2607
9  10  Female   38     Returning       Business  Business             2822

   Departure Delay  Arrival Delay  Departure and Arrival Time Convenience  \
0                2            5.0                                       3
1               26           39.0                                       2
2                0            0.0                                       4
3                0            0.0                                       2
4                0            1.0                                       3
5                0            0.0                                       4
6                0            0.0                                       3
7                0            3.0                                       3
8                0            0.0                                       1
9               13            0.0                                       2

   ...  On-board Service  Seat Comfort  Leg Room Service  Cleanliness  \
0  ...                 3             5                 2            5
1  ...                 5             4                 5            5
2  ...                 3             5                 3            5
3  ...                 5             5                 5            4
4  ...                 3             4                 4            5
5  ...                 4             4                 4            3
6  ...                 5             5                 5            4
7  ...                 3             4                 4            4
8  ...                 4             3                 4            3
9  ...                 5             4                 5            4

   Food and Drink  In-flight Service  In-flight Wifi Service  \
0               5                  5                       3
1               3                  5                       2
2               5                  3                       4
3               4                  5                       2
4               4                  3                       3
5               3                  4                       4
6               5                  5                       3
7               4                  3                       4
8               3                  4                       4
9               2                  5                       2

   In-flight Entertainment  Baggage Handling             Satisfaction
0                        5                 5  Neutral or Dissatisfied
1                        5                 5                Satisfied
2                        3                 3                Satisfied
3                        5                 5                Satisfied
4                        3                 3                Satisfied
5                        4                 4                Satisfied
6                        5                 5                Satisfied
7                        3                 3                Satisfied
8                        4                 4  Neutral or Dissatisfied
9                        5                 5                Satisfied

[10 rows x 24 columns]
            ID  Gender  Age Customer Type Type of Travel         Class  \
129870  129871  Female   23    First-time       Business      Business
129871  129872  Female   32     Returning       Business  Economy Plus
129872  129873  Female   44     Returning       Personal  Economy Plus
129873  129874  Female   28     Returning       Personal  Economy Plus
129874  129875  Female   55     Returning       Personal  Economy Plus
129875  129876    Male   28     Returning       Personal  Economy Plus
129876  129877    Male   41     Returning       Personal  Economy Plus
129877  129878    Male   42     Returning       Personal  Economy Plus
129878  129879    Male   50     Returning       Personal  Economy Plus
129879  129880  Female   20     Returning       Personal  Economy Plus

        Flight Distance  Departure Delay  Arrival Delay  \
129870              337               46           58.0
129871              337                0            1.0
129872              308                0           22.0
129873              337                0            0.0
129874              308                0            0.0
129875              447                2            3.0
129876              308                0            0.0
129877              337                6           14.0
129878              337               31           22.0
129879              337                0            0.0

        Departure and Arrival Time Convenience  ...  On-board Service  \
129870                                       2  ...                 2
129871                                       2  ...                 5
129872                                       4  ...                 3
129873                                       2  ...                 1
129874                                       4  ...                 4
129875                                       4  ...                 5
129876                                       5  ...                 5
129877                                       5  ...                 3
129878                                       4  ...                 4
129879                                       1  ...                 4

        Seat Comfort  Leg Room Service  Cleanliness  Food and Drink  \
129870             5                 1            5               5
129871             4                 1            4               4
129872             4                 3            5               5
129873             3                 5            3               3
129874             3                 3            4               2
129875             1                 4            4               4
129876             2                 5            2               2
129877             3                 4            3               3
129878             4                 5            3               3
129879             2                 4            2               2

        In-flight Service  In-flight Wifi Service  In-flight Entertainment  \
129870                  4                       2                        5
129871                  1                       4                        4
129872                  3                       3                        3
129873                  4                       4                        3
129874                  4                       3                        4
129875                  5                       4                        4
129876                  4                       3                        2
129877                  4                       2                        3
129878                  4                       5                        3
129879                  2                       3                        2

        Baggage Handling             Satisfaction
129870                 4  Neutral or Dissatisfied
129871                 3                Satisfied
129872                 3  Neutral or Dissatisfied
129873                 3  Neutral or Dissatisfied
129874                 4  Neutral or Dissatisfied
129875                 4  Neutral or Dissatisfied
129876                 5  Neutral or Dissatisfied
129877                 5  Neutral or Dissatisfied
129878                 5                Satisfied
129879                 1  Neutral or Dissatisfied

[10 rows x 24 columns]

In [10]:
data.columns

Index(['ID', 'Gender', 'Age', 'Customer Type', 'Type of Travel', 'Class',
       'Flight Distance', 'Departure Delay', 'Arrival Delay',
       'Departure and Arrival Time Convenience', 'Ease of Online Booking',
       'Check-in Service', 'Online Boarding', 'Gate Location',
       'On-board Service', 'Seat Comfort', 'Leg Room Service', 'Cleanliness',
       'Food and Drink', 'In-flight Service', 'In-flight Wifi Service',
       'In-flight Entertainment', 'Baggage Handling', 'Satisfaction'],
      dtype='object')

In [11]:
#removing unwanted columns
data=data.drop(columns=['ID','Ease of Online Booking', 'Gate Location'])

In [12]:
data.columns

Index(['Gender', 'Age', 'Customer Type', 'Type of Travel', 'Class',
       'Flight Distance', 'Departure Delay', 'Arrival Delay',
       'Departure and Arrival Time Convenience', 'Check-in Service',
       'Online Boarding', 'On-board Service', 'Seat Comfort',
       'Leg Room Service', 'Cleanliness', 'Food and Drink',
       'In-flight Service', 'In-flight Wifi Service',
       'In-flight Entertainment', 'Baggage Handling', 'Satisfaction'],
      dtype='object')

In [13]:
data.isnull().sum()

Gender                                      0
Age                                         0
Customer Type                               0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Departure Delay                             0
Arrival Delay                             393
Departure and Arrival Time Convenience      0
Check-in Service                            0
Online Boarding                             0
On-board Service                            0
Seat Comfort                                0
Leg Room Service                            0
Cleanliness                                 0
Food and Drink                              0
In-flight Service                           0
In-flight Wifi Service                      0
In-flight Entertainment                     0
Baggage Handling                            0
Satisfaction                                0
dtype: int64

In [14]:
#spliting feature column and target column
x=data.drop(columns=['Satisfaction'])

#target
y=data['Satisfaction']

In [15]:
num_x= x.select_dtypes(include="number").columns.tolist()
cat_x=x.select_dtypes(exclude='number').columns.tolist()

In [26]:
print("columns that are numeric",num_x)
print("columns that are categorical",cat_x)

columns that are numeric ['Age', 'Flight Distance', 'Departure Delay', 'Arrival Delay', 'Departure and Arrival Time Convenience', 'Check-in Service', 'Online Boarding', 'On-board Service', 'Seat Comfort', 'Leg Room Service', 'Cleanliness', 'Food and Drink', 'In-flight Service', 'In-flight Wifi Service', 'In-flight Entertainment', 'Baggage Handling']
columns that are categorical ['Gender', 'Customer Type', 'Type of Travel', 'Class']

In [17]:
num_transformation=Pipeline(steps=[("imputer", SimpleImputer(strategy="median")),
                                   ("scaling", StandardScaler())])
cat_transformation=Pipeline(steps=[("imputer", SimpleImputer(strategy="most_frequent")),
                                   ("onehot", OneHotEncoder(handle_unknown="ignore"))])

preprocessor= ColumnTransformer(transformers=[("num", num_transformation, num_x),
                                             ("cat", cat_transformation , cat_x)],
                               remainder="drop")
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['Age', 'Flight Distance', 'Departure Delay',
                                  'Arrival Delay',
                                  'Departure and Arrival Time Convenience',
                                  'Check-in Service', 'Online Boarding',
                                  'On-board Service', 'Seat Comfort',
                                  'Leg Room Service', 'Cleanliness',
                                  'Food and Drink', 'In-flight Service',
                                  'In-flight Wifi Service',
                                  'In-flight Entertainment',
                                  'Baggage Handling']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Gender', 'Customer Type', 'Type of Travel',
                                  'Class'])])

In [18]:
le = LabelEncoder()

y = le.fit_transform(y)
print(y)

[0 1 1 ... 0 1 0]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(103904, 20)
(25976, 20)

In [34]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print(X_train_processed)
#print(X_test_processed)

[[-0.16104991  0.99298216  0.0840723  ...  1.          0.
   0.        ]
 [-1.94738547 -1.05925965 12.42527409 ...  0.          1.
   0.        ]
 [-1.21961913 -0.88807265 -0.36136386 ...  0.          1.
   0.        ]
 ...
 [-1.28577971 -1.08128371 -0.38756598 ...  0.          1.
   0.        ]
 [-0.22721049 -1.05125091  0.66051909 ...  0.          1.
   0.        ]
 [-0.62417395 -0.84702782  1.49898716 ...  0.          1.
   0.        ]]

In [21]:
#neural network modules
from keras.models import Sequential
from keras.layers import Dense, Activation
#from keras.utilts import np_utilts
import tensorflow as tf

In [22]:
X_train.shape[1] #how many x columns are there

20

In [27]:
model=Sequential()


model.add(Dense(32, input_dim=X_train_processed.shape[1], activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
model.compile(
    loss='binary_crossentropy', #error
    optimizer='adam', #gradient decent
    metrics=['accuracy'] #accuracy
)

In [31]:
#training the data
model.fit( X_train_processed,y_train,
    validation_data=( X_test_processed, y_test),
    batch_size=32,
    epochs=50)

Epoch 1/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9490 - loss: 0.1219 - val_accuracy: 0.9471 - val_loss: 0.1215
Epoch 2/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9532 - loss: 0.1106 - val_accuracy: 0.9562 - val_loss: 0.1054
Epoch 3/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9562 - loss: 0.1035 - val_accuracy: 0.9552 - val_loss: 0.1071
Epoch 4/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9583 - loss: 0.0990 - val_accuracy: 0.9588 - val_loss: 0.1002
Epoch 5/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9592 - loss: 0.0957 - val_accuracy: 0.9570 - val_loss: 0.1033
Epoch 6/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9604 - loss: 0.0934 - val_accuracy: 0.9600 - val_loss: 0.0946
Epoch 7/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9614 - loss: 0.0905 - val_accuracy: 0.9584 - val_loss: 0.0995
Epoch 8/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9617 - loss: 0.0886 - val_accuracy: 0.9607 - val_loss: 0.0943
Epoch 9/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9628 - loss: 0.0866 - val_accuracy: 0.9605 - val_loss: 0.0935
Epoch 10/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9635 - loss: 0.0852 - val_accuracy: 0.9587 - val_loss: 0.0971
Epoch 11/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9638 - loss: 0.0843 - val_accuracy: 0.9610 - val_loss: 0.0930
Epoch 12/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9641 - loss: 0.0831 - val_accuracy: 0.9624 - val_loss: 0.0913
Epoch 13/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9645 - loss: 0.0818 - val_accuracy: 0.9627 - val_loss: 0.0944
Epoch 14/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9652 - loss: 0.0804 - val_accuracy: 0.9625 - val_loss: 0.0947
Epoch 15/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9652 - loss: 0.0804 - val_accuracy: 0.9615 - val_loss: 0.0992
Epoch 16/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9656 - loss: 0.0795 - val_accuracy: 0.9608 - val_loss: 0.0929
Epoch 17/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9662 - loss: 0.0779 - val_accuracy: 0.9617 - val_loss: 0.0973
Epoch 18/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9659 - loss: 0.0780 - val_accuracy: 0.9626 - val_loss: 0.0941
Epoch 19/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9664 - loss: 0.0764 - val_accuracy: 0.9633 - val_loss: 0.0937
Epoch 20/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9668 - loss: 0.0762 - val_accuracy: 0.9627 - val_loss: 0.0925
Epoch 21/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9671 - loss: 0.0756 - val_accuracy: 0.9611 - val_loss: 0.0948
Epoch 22/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9672 - loss: 0.0749 - val_accuracy: 0.9583 - val_loss: 0.1159
Epoch 23/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9677 - loss: 0.0741 - val_accuracy: 0.9625 - val_loss: 0.0967
Epoch 24/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9675 - loss: 0.0738 - val_accuracy: 0.9632 - val_loss: 0.0936
Epoch 25/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9678 - loss: 0.0734 - val_accuracy: 0.9625 - val_loss: 0.0962
Epoch 26/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9681 - loss: 0.0725 - val_accuracy: 0.9640 - val_loss: 0.0979
Epoch 27/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9683 - loss: 0.0723 - val_accuracy: 0.9631 - val_loss: 0.0998
Epoch 28/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9684 - loss: 0.0714 - val_accuracy: 0.9623 - val_loss: 0.0995
Epoch 29/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9687 - loss: 0.0711 - val_accuracy: 0.9622 - val_loss: 0.0987
Epoch 30/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9689 - loss: 0.0703 - val_accuracy: 0.9632 - val_loss: 0.0938
Epoch 31/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9688 - loss: 0.0697 - val_accuracy: 0.9644 - val_loss: 0.0943
Epoch 32/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9693 - loss: 0.0691 - val_accuracy: 0.9627 - val_loss: 0.0972
Epoch 33/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9696 - loss: 0.0688 - val_accuracy: 0.9627 - val_loss: 0.1049
Epoch 34/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9694 - loss: 0.0683 - val_accuracy: 0.9635 - val_loss: 0.0977
Epoch 35/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9701 - loss: 0.0673 - val_accuracy: 0.9628 - val_loss: 0.0973
Epoch 36/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9703 - loss: 0.0668 - val_accuracy: 0.9620 - val_loss: 0.1007
Epoch 37/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9701 - loss: 0.0668 - val_accuracy: 0.9628 - val_loss: 0.0976
Epoch 38/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9708 - loss: 0.0657 - val_accuracy: 0.9624 - val_loss: 0.1048
Epoch 39/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9706 - loss: 0.0656 - val_accuracy: 0.9595 - val_loss: 0.1156
Epoch 40/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9710 - loss: 0.0653 - val_accuracy: 0.9623 - val_loss: 0.1021
Epoch 41/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9709 - loss: 0.0645 - val_accuracy: 0.9623 - val_loss: 0.1082
Epoch 42/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - accuracy: 0.9710 - loss: 0.0648 - val_accuracy: 0.9617 - val_loss: 0.1081
Epoch 43/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - accuracy: 0.9716 - loss: 0.0632 - val_accuracy: 0.9623 - val_loss: 0.1052
Epoch 44/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9717 - loss: 0.0640 - val_accuracy: 0.9620 - val_loss: 0.1114
Epoch 45/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - accuracy: 0.9718 - loss: 0.0625 - val_accuracy: 0.9613 - val_loss: 0.1106
Epoch 46/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9716 - loss: 0.0627 - val_accuracy: 0.9608 - val_loss: 0.1094
Epoch 47/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9723 - loss: 0.0613 - val_accuracy: 0.9608 - val_loss: 0.1115
Epoch 48/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9723 - loss: 0.0616 - val_accuracy: 0.9597 - val_loss: 0.1213
Epoch 49/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9723 - loss: 0.0606 - val_accuracy: 0.9599 - val_loss: 0.1173
Epoch 50/50
3247/3247 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9725 - loss: 0.0612 - val_accuracy: 0.9608 - val_loss: 0.1175